<?php
declare(strict_types=1);
namespace VMM\Multilingual\Admin;
use VMM\Multilingual\Site\{Languages,PluginTranslations as Strings,ContentTranslations as Content};
final class PluginScreen
{
    public function __construct(private readonly Strings $strings){}
    public function register(): void {
        add_action('admin_enqueue_scripts',static function(){if(($_GET['page']??'')==='vmm-plugins'){wp_enqueue_media();wp_enqueue_editor();wp_enqueue_script('vmm-plugin-resources',plugins_url('assets/plugin-resources.js',dirname(__DIR__,2).'/vmm-multilingual.php'),['editor'],(string)filemtime(dirname(__DIR__,2).'/assets/plugin-resources.js'),true);wp_enqueue_style('vmm-plugin-resources',plugins_url('assets/plugin-resources.css',dirname(__DIR__,2).'/vmm-multilingual.php'),[],(string)filemtime(dirname(__DIR__,2).'/assets/plugin-resources.css'));}});
        add_action('admin_post_vmm_discovery',static function(){
            if(!current_user_can('manage_options'))wp_die('Keine Berechtigung.');check_admin_referer('vmm_discovery');
            $key='vmm_discovery_'.get_current_user_id();if(($_POST['mode']??'')==='start')set_transient($key,1,15*MINUTE_IN_SECONDS);else delete_transient($key);
            wp_safe_redirect(add_query_arg(['page'=>'vmm-plugins','plugin'=>sanitize_text_field(wp_unslash($_POST['plugin']??'')),'locale'=>sanitize_text_field($_POST['locale']??''),...PluginList::filters($_POST)],admin_url('admin.php')));exit;
        });
        add_action('admin_menu',function(){add_submenu_page('vmm-multilingual','Plugin-Inhalte','Plugin-Inhalte','manage_options','vmm-plugins',[$this,'render']);},20);
        add_action('admin_post_vmm_plugin_save',function(){if(!current_user_can('manage_options'))wp_die('Keine Berechtigung.');check_admin_referer('vmm_plugin');try{$plugin=sanitize_text_field(wp_unslash($_POST['plugin']??''));$locale=sanitize_text_field($_POST['locale']??'');$fields=wp_unslash($_POST['fields']??[]);if(!is_array($fields))throw new \InvalidArgumentException('Ungültige Eingabe.');$this->strings->save($plugin,$locale,$fields,absint($_POST['revision']??0),sanitize_text_field($_POST['source_hash']??''));wp_safe_redirect(add_query_arg(['page'=>'vmm-plugins','plugin'=>$plugin,'locale'=>$locale,'saved'=>1,...PluginList::filters($_POST),'offset'=>absint($_POST['offset']??0)],admin_url('admin.php')));exit;}catch(\Throwable $e){wp_die(esc_html($e->getMessage()),'Plugin-Übersetzung',['response'=>409,'back_link'=>true]);}});
        add_action('admin_post_vmm_field_rules',function(){if(!current_user_can('manage_options'))wp_die('Keine Berechtigung.');check_admin_referer('vmm_fields');$rules=wp_unslash($_POST['rules']??[]);if(!is_array($rules))wp_die('Ungültige Eingabe.');$old=(array)get_option('vmm_field_rules',[]);foreach($rules as $type=>$fields){if(!in_array($type,Content::types(),true)||!is_array($fields))wp_die('Ungültiger Inhaltstyp.');foreach($fields as $key=>$mode){if(!in_array($mode,['shared','text','textarea','image','url'],true)||str_starts_with($key,'_vmm_'))wp_die('Ungültige Feldregel.');$old[$type][$key]=$mode;}}update_option('vmm_field_rules',$old,false);wp_safe_redirect(admin_url('admin.php?page=vmm-settings&tab=fields&saved=1'));exit;});
    }
    public function render(): void {
        if(!current_user_can('manage_options'))wp_die('Keine Berechtigung.');$plugins=Strings::plugins();$plugin=sanitize_text_field(wp_unslash($_GET['plugin']??''));$locale=sanitize_text_field($_GET['locale']??'');$languages=array_diff_key(Languages::names(),[Languages::source()=>true]);if(!isset($languages[$locale]))$locale=array_key_first($languages)??'';
        $area=sanitize_key($_GET['area']??'');$areas=['website'=>'Website','email'=>'E-Mails','pdf'=>'PDFs','shared'=>'Textbausteine','system'=>'Systemtexte / Verwaltung'];if(!isset($areas[$area]))$area='';
        $filters=PluginList::filters($_GET);$filters['area']=$area;$search=$filters['search'];$offset=absint($_GET['offset']??0);
        echo '<div class="wrap"><h1>Plugin-Inhalte übersetzen</h1>';
        if(isset($_GET['saved']))echo '<div class="notice notice-success"><p>Übersetzungen gespeichert.</p></div>';
        echo '<form method="get" class="vmm-plugin-filters"><input type="hidden" name="page" value="vmm-plugins"><input type="hidden" name="kind" value="'.esc_attr($filters['kind']).'"><div class="vmm-filter-grid"><label>Plugin <select name="plugin"><option value="">Plugin auswählen</option>';foreach($plugins as $file=>$info)if(!str_starts_with($file,'vmm-multilingual/'))echo '<option value="'.esc_attr($file).'" '.selected($plugin,$file,false).'>'.esc_html($info['Name']).'</option>';echo '</select></label> <label>Sprache <select name="locale">';foreach($languages as $key=>$name)echo '<option value="'.esc_attr($key).'" '.selected($locale,$key,false).'>'.esc_html($name).'</option>';echo '</select></label> <label>Bereich <select name="area"><option value="">Alle Bereiche</option>';foreach($areas as $key=>$name)echo '<option value="'.$key.'" '.selected($area,$key,false).'>'.esc_html($name).'</option>';echo '</select></label> <label>Herkunft <select name="origin">';foreach(PluginList::ORIGINS as $key=>$name)echo '<option value="'.$key.'" '.selected($filters['origin'],$key,false).'>'.esc_html($name).'</option>';echo '</select></label> <label class="vmm-empty-filter">Leere Felder <input type="checkbox" name="empty" value="1" '.checked($filters['empty'],'1',false).' aria-label="Leere Felder anzeigen"></label> <label>Suche <input type="search" name="search" value="'.esc_attr($search).'"></label> <button class="button">Anzeigen / neu prüfen</button></div></form>';
        $active=(bool)get_transient('vmm_discovery_'.get_current_user_id());
        echo '<form method="post" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="vmm_discovery"><input type="hidden" name="mode" value="'.($active?'stop':'start').'"><input type="hidden" name="plugin" value="'.esc_attr($plugin).'"><input type="hidden" name="locale" value="'.esc_attr($locale).'">';foreach($filters as $key=>$value)echo '<input type="hidden" name="'.$key.'" value="'.esc_attr($value).'">';wp_nonce_field('vmm_discovery');
        echo '<p class="vmm-capture-actions"><button class="button '.($active?'button-primary':'').'">'.($active?'Erfassung beenden':'Texte beim Durchsehen erfassen').'</button></p></form>';
        if(!isset($plugins[$plugin])||$locale===''){echo '</div>';return;}
        foreach(apply_filters('vmm_plugin_issues',[],$plugin) as $issue)echo '<div class="notice notice-warning"><p>'.esc_html((string)$issue).'</p></div>';
        $rows=$this->strings->catalog($plugin,true);$data=(array)get_option(Strings::OPTION,[]);$doc=$data[$plugin]??[];$source=array_map(static fn($r)=>$r['source'],$rows);$hash=Content::hash($source);
        $display=array_map([PluginList::class,'decorate'],$rows);
        $eligible=array_filter($display,static fn($r)=>(!isset($r['form'])||$r['form']<Strings::pluralCount($locale))&&PluginList::matches($r,$filters,$doc['locales'][$locale][$r['key']]??null,true));
        echo '<nav class="nav-tab-wrapper vmm-kind-tabs" aria-label="Textarten">';
        foreach(PluginList::KINDS as $key=>$name){$count=count(array_filter($eligible,static fn($r)=>$key===''||$r['kind']===$key));echo '<a class="nav-tab '.($filters['kind']===$key?'nav-tab-active':'').'" '.($filters['kind']===$key?'aria-current="page"':'').' href="'.esc_url(add_query_arg(['page'=>'vmm-plugins','plugin'=>$plugin,'locale'=>$locale,...$filters,'kind'=>$key,'offset'=>0],admin_url('admin.php'))).'">'.esc_html($name).' <span class="count">('.$count.')</span></a>';}
        echo '</nav>';
        $filtered=array_filter($eligible,static fn($r)=>$filters['kind']===''||$r['kind']===$filters['kind']);
        uasort($filtered,static fn($a,$b)=>strnatcasecmp($a['group'],$b['group']));
        if($offset>=count($filtered))$offset=0;$visible=array_slice($filtered,$offset,60,true);
        echo '<p><strong>Einträge '.(count($filtered)?$offset+1:0).'–'.min($offset+60,count($filtered)).' von '.count($filtered).'</strong></p>';
        for($start=0;$start<count($filtered);$start+=60)echo '<a class="button" '.($start===$offset?'aria-current="page"':'').' href="'.esc_url(add_query_arg(['page'=>'vmm-plugins','plugin'=>$plugin,'locale'=>$locale,...$filters,'offset'=>$start],admin_url('admin.php'))).'">Seite '.(int)($start/60+1).'</a> ';
        echo '<form method="post" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="vmm_plugin_save">';wp_nonce_field('vmm_plugin');foreach(['plugin'=>$plugin,'locale'=>$locale,'revision'=>(int)($doc['revision']??0),'source_hash'=>$hash,...$filters,'offset'=>$offset] as $key=>$value)echo '<input type="hidden" name="'.$key.'" value="'.esc_attr((string)$value).'">';
        echo '<table class="widefat striped vmm-strings"><thead><tr><th>Ausgangswert</th><th style="width:240px">'.esc_html($languages[$locale]).'</th></tr></thead><tbody>';
        $lastGroup=null;
        if(!$visible)echo '<tr><td colspan="2">Keine Inhalte für diese Filter. Gegebenenfalls „Leere Felder anzeigen“ aktivieren oder Herkunft zurücksetzen.</td></tr>';
        foreach($visible as $key=>$row){
            if($lastGroup!==$row['group']){echo '<tr class="vmm-group"><th colspan="2" scope="colgroup">'.esc_html($row['group']).'</th></tr>';$lastGroup=$row['group'];}
            $record=$doc['locales'][$locale][$key]??null;$value=$record['value']??$row['source'];
            $tokens=implode(' ',array_unique(Strings::placeholders($row['source'])));
            $context=(string)($row['context']??'');$label=$row['label'];
            if($context!==''&&str_ends_with($label,' · '.$context))$label=substr($label,0,-strlen(' · '.$context));
            $empty=$row['source']===''?'Dieses Feld ist in der Ausgangssprache leer.':'';
            $contextHtml=$context!==''?'<div class="vmm-field-context"><span>Kontext / zugehöriges Element:</span> '.esc_html($context).'</div>':'';

            echo '<tr class="vmm-string" data-type="'.esc_attr($row['type']).'"><td><strong class="vmm-label">'.esc_html($label).'</strong> <small class="vmm-area">'.esc_html($areas[$row['area']??'system']??'Systemtexte').'</small>'.$contextHtml.'<div class="vmm-source-preview">'.esc_html($row['source']!==''?wp_strip_all_tags(preg_replace('~<(?:br\s*/?|/(?:p|li|h[1-6]|div))>~i',"\n",$row['source'])):$empty).'</div><span class="vmm-field-context-value" hidden>'.esc_html($context).'</span><pre class="vmm-source" hidden>'.esc_html($row['source']).'</pre><span class="vmm-hint" hidden>'.esc_html($row['hint']??'').'</span><span class="vmm-tokens" hidden>'.esc_html($tokens).'</span>';
            echo '<small class="vmm-origin">Herkunft: '.esc_html(implode(' · ',array_map(static fn($o)=>PluginList::ORIGINS[$o]??$o,$row['origins']))).'</small>';
            if($tokens!=='')echo '<small>Platzhalter: <code>'.esc_html($tokens).'</code></small>';
            if(!empty($row['path']))echo '<small class="vmm-path">'.esc_html($row['path']).'</small>';
            echo '</td><td><input class="vmm-mode" type="hidden" name="fields['.esc_attr($key).'][mode]" value="'.($record?'custom':'inherit').'"><textarea hidden class="vmm-value" name="fields['.esc_attr($key).'][value]">'.esc_textarea($value).'</textarea><div class="vmm-actions"><button type="button" class="button vmm-inherit" aria-pressed="'.($record?'false':'true').'">Übernehmen</button><button type="button" class="button vmm-translate" aria-pressed="'.($record?'true':'false').'">Übersetzen</button></div><small class="vmm-state">'.($record?'Eigene Übersetzung':'Ausgangssprache übernehmen').'</small>';
            if($record&&($record['source_hash']??'')!==Content::hash([$row['source']]))echo '<small class="vmm-outdated">Ausgangswert geändert · prüfen</small>';
            echo '</td></tr>';
        }
        echo '</tbody></table>';submit_button('Änderungen speichern');echo '</form>';
        echo '<dialog id="vmm-string-dialog" aria-labelledby="vmm-dialog-title"><header><h2 id="vmm-dialog-title">Übersetzung</h2><button type="button" class="button vmm-cancel" aria-label="Schließen">×</button></header><p id="vmm-dialog-context"></p><p id="vmm-dialog-hint"></p><div class="vmm-dialog-columns"><section><h3>'.esc_html(Languages::names()[Languages::source()]).' · Ausgangswert</h3><pre id="vmm-dialog-source"></pre><img id="vmm-dialog-source-image" alt="Bild der Ausgangssprache" hidden></section><section><label for="vmm-dialog-value"><h3>'.esc_html($languages[$locale]).' · Übersetzung</h3></label><textarea id="vmm-dialog-value" rows="10"></textarea><p><button type="button" class="button" id="vmm-dialog-copy">Ausgangswert kopieren</button> <button type="button" class="button" id="vmm-dialog-media">Bild auswählen</button></p></section></div><p id="vmm-dialog-tokens"></p><p>Platzhalter unverändert lassen. „In Liste übernehmen“ merkt die Bearbeitung vor; anschließend „Änderungen speichern“ klicken.</p><footer><button type="button" class="button vmm-cancel">Abbrechen</button><button type="button" class="button button-primary" id="vmm-dialog-apply">In Liste übernehmen</button></footer></dialog><p>';
        foreach(['Vorherige'=>max(0,$offset-60),'Nächste'=>$offset+60] as $label=>$next)if(($label==='Vorherige'&&$offset>0)||($label==='Nächste'&&$next<count($filtered)))echo '<a class="button" href="'.esc_url(add_query_arg(['page'=>'vmm-plugins','plugin'=>$plugin,'locale'=>$locale,...$filters,'offset'=>$next],admin_url('admin.php'))).'">'.$label.'</a> ';echo '</p></div>';
    }
    public function rules(): void {
        if(!current_user_can('manage_options'))wp_die('Keine Berechtigung.');global $wpdb;$rules=(array)get_option('vmm_field_rules',[]);
        echo '<div class="wrap"><h1>Custom-Field-Regeln</h1><p>Öffentliche Inhaltstypen sind automatisch übersetzbar. Öffentliche einfache Textfelder sind standardmäßig übersetzbar; geschützte Felder bleiben gemeinsam. Technische IDs und Preise auf „Gemeinsam“ belassen. Verschachtelte Textwerte werden einzeln übersetzt; Struktur und numerische IDs bleiben erhalten. Feldsysteme mit eigener Speicherung benötigen eine Integration.</p>';
        if(isset($_GET['saved']))echo '<div class="notice notice-success"><p>Feldregeln gespeichert.</p></div>';
        echo '<form method="post" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="vmm_field_rules">';wp_nonce_field('vmm_fields');
        foreach(Content::types() as $type){$keys=$wpdb->get_col($wpdb->prepare("SELECT DISTINCT pm.meta_key FROM {$wpdb->postmeta} pm INNER JOIN {$wpdb->posts} p ON p.ID=pm.post_id WHERE p.post_type=%s ORDER BY pm.meta_key LIMIT 100",$type));echo '<h2>'.esc_html(get_post_type_object($type)->labels->name).'</h2><table class="widefat striped"><tbody>';foreach($keys as $key){if(str_starts_with($key,'_vmm_')||str_starts_with($key,'_yoast_')||in_array($key,['_edit_lock','_edit_last','_thumbnail_id','_wp_page_template'],true))continue;$sample=$wpdb->get_var($wpdb->prepare("SELECT pm.meta_value FROM {$wpdb->postmeta} pm INNER JOIN {$wpdb->posts} p ON p.ID=pm.post_id WHERE p.post_type=%s AND pm.meta_key=%s LIMIT 1",$type,$key));$mode=$rules[$type][$key]??(!is_protected_meta($key,'post')&&!is_numeric(maybe_unserialize($sample))?'text':'shared');echo '<tr><th>'.esc_html($key).'</th><td><select aria-label="'.esc_attr($type.' '.$key).'" name="rules['.esc_attr($type).']['.esc_attr($key).']">';foreach(['shared'=>'Gemeinsam','text'=>'Text übersetzen','textarea'=>'Mehrzeiliger Text / HTML','image'=>'Bild-ID abweichend','url'=>'Link abweichend'] as $value=>$label)echo '<option value="'.$value.'" '.selected($mode,$value,false).'>'.$label.'</option>';echo '</select></td></tr>';}echo '</tbody></table>';}
        submit_button('Feldregeln speichern');echo '</form></div>';
    }
}
