'use strict';
const fs=require('fs'),vm=require('vm'),assert=require('assert/strict');const js=fs.readFileSync(__dirname+'/../assets/visual-editor.js','utf8');
const take=(a,b)=>js.slice(js.indexOf(a),js.indexOf(b,js.indexOf(a)));
const context={drafts:new Map(),fields:new Map(),sources:new Map(),steps:[],redos:[],journal:[],switching:false,restoring:false,active:null,busy:false,dirty:false,page:null,selected:null,panel:{querySelector:()=>null,replaceChildren(){}},renderDraftPreview(){},updateActions(){},syncRich(){},clearEditors(){},reloadFrame(){},el(){return {};},message(text,error){context.lastMessage={text,error};},c:{locale:'en_GB',source:'de_DE',id:2}};
vm.createContext(context);vm.runInContext(take(' const draftKey=',' function stageOperation(')+take(' const copy=',' async function moveHistory('),context);
let count=0;const ok=(v,msg)=>{assert.ok(v,msg);count++;};const inherit={mode:'inherit',value:''},custom=value=>({mode:'custom',value,confirmed_same:false});
const baseline={revision:0,master_hash:'source',records:{}};
function edit(kind,id,key,value){context.active={kind,identity:id,documentData:baseline,baseline:{[key]:inherit}};context.fields.clear();context.fields.set(key,custom(value));context.stash();}
edit('builder','one','content','First');edit('builder','two','content','Second');ok(context.drafts.size===2,'Switching elements preserves both drafts');
context.fields.set('content',inherit);context.stash();ok(context.drafts.size===1&&context.drafts.has('builder:one'),'Reverting one element retains the other draft');
context.drafts.clear();edit('native','content','content','Body');edit('native','page','title','Title');ok(context.drafts.size===1&&Object.keys(context.drafts.get('native:page').fields).length===2,'Native page fields merge without losing content');
context.drafts.clear();context.active=null;context.fields.clear();const state={revision:0,master_hash:'source',records:{}};let fail=false,writes=0;
context.request=async(path,data)=>{if(!data)return {builder:JSON.parse(JSON.stringify(state))};if(fail&&data.node==='two')throw Error('Validation failed');writes++;for(const [key,field] of Object.entries(data.fields)){state.records[data.node]??={};if(field.mode==='inherit')delete state.records[data.node][key];else state.records[data.node][key]={value:field.value,confirmed_same:!!field.confirmed_same};}state.revision++;return {builder:JSON.parse(JSON.stringify(state))};};
function prepare(){context.drafts.clear();state.records={};state.revision=0;context.steps.length=0;context.journal.length=0;writes=0;for(const id of ['one','two'])context.drafts.set('builder:'+id,{kind:'builder',identity:id,documentData:JSON.parse(JSON.stringify(state)),fields:{content:custom(id)}});context.dirty=true;}
(async()=>{prepare();state.records.one={content:{value:'Concurrent'}};await context.saveDrafts();ok(writes===0&&context.drafts.size===2,'Preflight conflict writes nothing and preserves both drafts');prepare();fail=true;await context.saveDrafts();ok(!state.records.one.content&&context.drafts.size===2,'Failed second element rolls back first and retains drafts');fail=false;prepare();await context.saveDrafts();ok(state.records.one.content.value==='one'&&state.records.two.content.value==='two','One save persists all elements');ok(!context.dirty&&context.drafts.size===0,'Successful save clears drafts');ok(context.steps.length===1&&context.steps[0].group&&context.steps[0].operations.length===2,'Batch save is a single reversible action');console.log('PASS '+count+' multi-element draft checks');})().catch(error=>{console.error(error);process.exitCode=1;});
