'use strict';
const fs=require('fs'),vm=require('vm'),assert=require('assert/strict');
const source=fs.readFileSync(__dirname+'/../assets/visual-editor.js','utf8');
const helpers=source.slice(source.indexOf(' function fieldState('),source.indexOf(' async function moveHistory('));
const context={c:{locale:'en_GB',source:'de_DE',id:2},sessionDocs:new Map(),request:async()=>{throw Error('Unexpected request');}};context.normalizeValue=value=>String(value??'').replace(/<\/?p(?:\s[^>]*)?>|<br\s*\/?>/gi,' ').replace(/\s+/g,' ').trim();vm.createContext(context);vm.runInContext(helpers,context);
let count=0;const check=(actual,expected)=>{assert.equal(actual,expected);count++;};
check(context.fieldState('Original',null).name,'inherit');
check(context.fieldState('Original',{mode:'inherit',value:'Other'}).name,'inherit');
check(context.fieldState('Original',{mode:'custom',value:''}).name,'empty');
check(context.fieldState('Original',{mode:'custom',value:'Original'}).name,'same');
check(context.fieldState('Original',{mode:'custom',value:'Original',confirmed_same:true}).name,'translated');
check(context.fieldState('Original',{mode:'custom',value:'Translation'}).name,'translated');
check(context.fieldState('Original',{mode:'custom',value:'<p>Original</p>'}).name,'same');
check(context.fieldState('',{mode:'custom',value:''}).name,'inherit');
const before={kind:'native',identity:'page',documentData:{revision:1,source_hash:'source',records:{title:{value:'Old',confirmed_same:false}}}};
const step=context.operation(before,['title']);
const current={revision:2,source_hash:'source',records:{title:{value:'New',confirmed_same:false}}};step.after=context.operation({...before,documentData:current},['title']);
let writes=0;context.request=async(path,data)=>{if(!data)return {native:current};writes++;check(data.fields.title.value,'Old');check(data.revision,2);return {native:before.documentData};};
(async()=>{await context.reverse(step);check(writes,1);current.records.title.value='Concurrent edit';await assert.rejects(context.reverse(step),/inzwischen geändert/);count++;check(writes,1);current.records.title.value='New';current.source_hash='Changed source';await assert.rejects(context.reverse(step),/inzwischen geändert/);count++;check(writes,1);console.log('PASS '+count+' visual status and undo checks');})().catch(error=>{console.error(error);process.exitCode=1;});
